/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddLessonWithWordsRequest {
  'title' : string,
  'content' : string,
  'ayahs' : Array<Ayah>,
  'visibleToStudents' : boolean,
  'words' : Array<Word>,
}
export interface AddLessonWithWordsResponse {
  'lessonId' : string,
  'wordsAdded' : bigint,
  'ayahsAdded' : bigint,
}
export interface Ayah {
  'text' : string,
  'reference' : [] | [string],
  'translation' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Lesson {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'author' : Principal,
  'updatedAt' : [] | [Time],
  'visibleToStudents' : boolean,
}
export interface LessonWithWords { 'lesson' : Lesson, 'words' : Array<Word> }
export interface Note {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'user' : Principal,
  'noteType' : NoteType,
  'updatedAt' : [] | [Time],
  'associatedId' : string,
}
export type NoteType = { 'ayah' : null } |
  { 'word' : null };
export interface Quiz {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'author' : Principal,
  'updatedAt' : [] | [Time],
  'quizType' : QuizType,
}
export type QuizType = { 'wordGuess' : null } |
  { 'multipleChoice' : null };
export interface StableUserProfile {
  'name' : string,
  'role' : string,
  'principalId' : string,
  'avatar' : [] | [ExternalBlob],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Word {
  'forms' : Array<string>,
  'lessonId' : string,
  'formMeanings' : Array<string>,
  'arabic' : string,
  'albanianMeanings' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAyahToLesson' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    undefined
  >,
  'addLessonWithWordsAndAyahs' : ActorMethod<
    [AddLessonWithWordsRequest],
    AddLessonWithWordsResponse
  >,
  'addWordToLesson' : ActorMethod<
    [string, Array<string>, Array<string>, Array<string>, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkWordInLessons' : ActorMethod<[string], boolean>,
  'createLesson' : ActorMethod<[string, string, boolean], string>,
  'createNote' : ActorMethod<[string, string, NoteType], string>,
  'createQuiz' : ActorMethod<[QuizType, string], string>,
  'deleteLesson' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'deleteQuiz' : ActorMethod<[string], undefined>,
  'deleteWordFromLesson' : ActorMethod<[string, string], undefined>,
  'getActiveLessonWithWords' : ActorMethod<[], [] | [LessonWithWords]>,
  'getActiveLessonWithWordsAndAyahs' : ActorMethod<
    [],
    [] | [{ 'ayahs' : Array<Ayah>, 'lesson' : Lesson, 'words' : Array<Word> }]
  >,
  'getAllActiveLessons' : ActorMethod<[], Array<Lesson>>,
  'getAllLessons' : ActorMethod<[], Array<Lesson>>,
  'getAllLessonsWithWordsAndAyahs' : ActorMethod<
    [],
    Array<{ 'ayahs' : Array<Ayah>, 'lesson' : Lesson, 'words' : Array<Word> }>
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<StableUserProfile>>,
  'getAllVocabulary' : ActorMethod<[], Array<Word>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StableUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLessonAyahs' : ActorMethod<[string], Array<Ayah>>,
  'getLessonById' : ActorMethod<
    [string],
    [] | [{ 'ayahs' : Array<Ayah>, 'lesson' : Lesson, 'words' : Array<Word> }]
  >,
  'getLessonWords' : ActorMethod<[], Array<[string, Array<string>]>>,
  'getLessonsByAuthor' : ActorMethod<[Principal], Array<Lesson>>,
  'getNotesByAssociatedId' : ActorMethod<[Principal, string], Array<Note>>,
  'getNotesByUser' : ActorMethod<[Principal], Array<Note>>,
  'getQuiz' : ActorMethod<[string], [] | [Quiz]>,
  'getQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getRandomWords' : ActorMethod<[], Array<Word>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StableUserProfile]>,
  'getVisibleLessons' : ActorMethod<[], Array<Lesson>>,
  'getWordsByLesson' : ActorMethod<[string], Array<Word>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteToTeacher' : ActorMethod<[Principal], undefined>,
  'registerProfile' : ActorMethod<[string], undefined>,
  'resetAppData' : ActorMethod<[], undefined>,
  'setLessonActive' : ActorMethod<[string, boolean], undefined>,
  'setLessonVisibility' : ActorMethod<[string, boolean], undefined>,
  'updateLesson' : ActorMethod<[string, string, string, boolean], undefined>,
  'updateLessonAyah' : ActorMethod<
    [string, bigint, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateNote' : ActorMethod<[string, string], undefined>,
  'updateProfile' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'updateQuiz' : ActorMethod<[string, string, QuizType], undefined>,
  'updateWord' : ActorMethod<
    [string, Array<string>, Array<string>, Array<string>, string],
    undefined
  >,
  'uploadLessonMaterial' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];