/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Ayah = IDL.Record({
  'text' : IDL.Text,
  'reference' : IDL.Opt(IDL.Text),
  'translation' : IDL.Opt(IDL.Text),
});
export const Word = IDL.Record({
  'forms' : IDL.Vec(IDL.Text),
  'lessonId' : IDL.Text,
  'formMeanings' : IDL.Vec(IDL.Text),
  'arabic' : IDL.Text,
  'albanianMeanings' : IDL.Vec(IDL.Text),
});
export const AddLessonWithWordsRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'ayahs' : IDL.Vec(Ayah),
  'visibleToStudents' : IDL.Bool,
  'words' : IDL.Vec(Word),
});
export const AddLessonWithWordsResponse = IDL.Record({
  'lessonId' : IDL.Text,
  'wordsAdded' : IDL.Nat,
  'ayahsAdded' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NoteType = IDL.Variant({ 'ayah' : IDL.Null, 'word' : IDL.Null });
export const QuizType = IDL.Variant({
  'wordGuess' : IDL.Null,
  'multipleChoice' : IDL.Null,
});
export const Time = IDL.Int;
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Opt(Time),
  'visibleToStudents' : IDL.Bool,
});
export const LessonWithWords = IDL.Record({
  'lesson' : Lesson,
  'words' : IDL.Vec(Word),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StableUserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'principalId' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'noteType' : NoteType,
  'updatedAt' : IDL.Opt(Time),
  'associatedId' : IDL.Text,
});
export const Quiz = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Opt(Time),
  'quizType' : QuizType,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAyahToLesson' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addLessonWithWordsAndAyahs' : IDL.Func(
      [AddLessonWithWordsRequest],
      [AddLessonWithWordsResponse],
      [],
    ),
  'addWordToLesson' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkWordInLessons' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createLesson' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Text], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, NoteType], [IDL.Text], []),
  'createQuiz' : IDL.Func([QuizType, IDL.Text], [IDL.Text], []),
  'deleteLesson' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'deleteQuiz' : IDL.Func([IDL.Text], [], []),
  'deleteWordFromLesson' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getActiveLessonWithWords' : IDL.Func(
      [],
      [IDL.Opt(LessonWithWords)],
      ['query'],
    ),
  'getActiveLessonWithWordsAndAyahs' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'ayahs' : IDL.Vec(Ayah),
            'lesson' : Lesson,
            'words' : IDL.Vec(Word),
          })
        ),
      ],
      ['query'],
    ),
  'getAllActiveLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getAllLessonsWithWordsAndAyahs' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'ayahs' : IDL.Vec(Ayah),
            'lesson' : Lesson,
            'words' : IDL.Vec(Word),
          })
        ),
      ],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(StableUserProfile)], ['query']),
  'getAllVocabulary' : IDL.Func([], [IDL.Vec(Word)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(StableUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLessonAyahs' : IDL.Func([IDL.Text], [IDL.Vec(Ayah)], ['query']),
  'getLessonById' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'ayahs' : IDL.Vec(Ayah),
            'lesson' : Lesson,
            'words' : IDL.Vec(Word),
          })
        ),
      ],
      ['query'],
    ),
  'getLessonWords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getLessonsByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Lesson)],
      ['query'],
    ),
  'getNotesByAssociatedId' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(Note)],
      ['query'],
    ),
  'getNotesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Note)], ['query']),
  'getQuiz' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
  'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getRandomWords' : IDL.Func([], [IDL.Vec(Word)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StableUserProfile)],
      ['query'],
    ),
  'getVisibleLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getWordsByLesson' : IDL.Func([IDL.Text], [IDL.Vec(Word)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteToTeacher' : IDL.Func([IDL.Principal], [], []),
  'registerProfile' : IDL.Func([IDL.Text], [], []),
  'resetAppData' : IDL.Func([], [], []),
  'setLessonActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setLessonVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateLesson' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateLessonAyah' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'updateQuiz' : IDL.Func([IDL.Text, IDL.Text, QuizType], [], []),
  'updateWord' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadLessonMaterial' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Ayah = IDL.Record({
    'text' : IDL.Text,
    'reference' : IDL.Opt(IDL.Text),
    'translation' : IDL.Opt(IDL.Text),
  });
  const Word = IDL.Record({
    'forms' : IDL.Vec(IDL.Text),
    'lessonId' : IDL.Text,
    'formMeanings' : IDL.Vec(IDL.Text),
    'arabic' : IDL.Text,
    'albanianMeanings' : IDL.Vec(IDL.Text),
  });
  const AddLessonWithWordsRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'ayahs' : IDL.Vec(Ayah),
    'visibleToStudents' : IDL.Bool,
    'words' : IDL.Vec(Word),
  });
  const AddLessonWithWordsResponse = IDL.Record({
    'lessonId' : IDL.Text,
    'wordsAdded' : IDL.Nat,
    'ayahsAdded' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NoteType = IDL.Variant({ 'ayah' : IDL.Null, 'word' : IDL.Null });
  const QuizType = IDL.Variant({
    'wordGuess' : IDL.Null,
    'multipleChoice' : IDL.Null,
  });
  const Time = IDL.Int;
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Opt(Time),
    'visibleToStudents' : IDL.Bool,
  });
  const LessonWithWords = IDL.Record({
    'lesson' : Lesson,
    'words' : IDL.Vec(Word),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StableUserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'principalId' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'noteType' : NoteType,
    'updatedAt' : IDL.Opt(Time),
    'associatedId' : IDL.Text,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Opt(Time),
    'quizType' : QuizType,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAyahToLesson' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addLessonWithWordsAndAyahs' : IDL.Func(
        [AddLessonWithWordsRequest],
        [AddLessonWithWordsResponse],
        [],
      ),
    'addWordToLesson' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkWordInLessons' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createLesson' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Text], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, NoteType], [IDL.Text], []),
    'createQuiz' : IDL.Func([QuizType, IDL.Text], [IDL.Text], []),
    'deleteLesson' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'deleteQuiz' : IDL.Func([IDL.Text], [], []),
    'deleteWordFromLesson' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getActiveLessonWithWords' : IDL.Func(
        [],
        [IDL.Opt(LessonWithWords)],
        ['query'],
      ),
    'getActiveLessonWithWordsAndAyahs' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'ayahs' : IDL.Vec(Ayah),
              'lesson' : Lesson,
              'words' : IDL.Vec(Word),
            })
          ),
        ],
        ['query'],
      ),
    'getAllActiveLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getAllLessonsWithWordsAndAyahs' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'ayahs' : IDL.Vec(Ayah),
              'lesson' : Lesson,
              'words' : IDL.Vec(Word),
            })
          ),
        ],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(StableUserProfile)],
        ['query'],
      ),
    'getAllVocabulary' : IDL.Func([], [IDL.Vec(Word)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(StableUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLessonAyahs' : IDL.Func([IDL.Text], [IDL.Vec(Ayah)], ['query']),
    'getLessonById' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'ayahs' : IDL.Vec(Ayah),
              'lesson' : Lesson,
              'words' : IDL.Vec(Word),
            })
          ),
        ],
        ['query'],
      ),
    'getLessonWords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getLessonsByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Lesson)],
        ['query'],
      ),
    'getNotesByAssociatedId' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(Note)],
        ['query'],
      ),
    'getNotesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Note)], ['query']),
    'getQuiz' : IDL.Func([IDL.Text], [IDL.Opt(Quiz)], ['query']),
    'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getRandomWords' : IDL.Func([], [IDL.Vec(Word)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StableUserProfile)],
        ['query'],
      ),
    'getVisibleLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getWordsByLesson' : IDL.Func([IDL.Text], [IDL.Vec(Word)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteToTeacher' : IDL.Func([IDL.Principal], [], []),
    'registerProfile' : IDL.Func([IDL.Text], [], []),
    'resetAppData' : IDL.Func([], [], []),
    'setLessonActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setLessonVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateLesson' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
    'updateLessonAyah' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'updateQuiz' : IDL.Func([IDL.Text, IDL.Text, QuizType], [], []),
    'updateWord' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadLessonMaterial' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };