/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StableUserProfile {
    name: string;
    role: string;
    principalId: string;
    avatar?: ExternalBlob;
}
export type Time = bigint;
export interface AddLessonWithWordsResponse {
    lessonId: string;
    wordsAdded: bigint;
    ayahsAdded: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Quiz {
    id: string;
    title: string;
    createdAt: Time;
    author: Principal;
    updatedAt?: Time;
    quizType: QuizType;
}
export interface AddLessonWithWordsRequest {
    title: string;
    content: string;
    ayahs: Array<Ayah>;
    visibleToStudents: boolean;
    words: Array<Word>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lesson {
    id: string;
    title: string;
    content: string;
    createdAt: Time;
    isActive: boolean;
    author: Principal;
    updatedAt?: Time;
    visibleToStudents: boolean;
}
export interface Ayah {
    text: string;
    reference?: string;
    translation?: string;
}
export interface Word {
    forms: Array<string>;
    lessonId: string;
    formMeanings: Array<string>;
    arabic: string;
    albanianMeanings: Array<string>;
}
export interface LessonWithWords {
    lesson: Lesson;
    words: Array<Word>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Note {
    id: string;
    content: string;
    createdAt: Time;
    user: Principal;
    noteType: NoteType;
    updatedAt?: Time;
    associatedId: string;
}
export enum NoteType {
    ayah = "ayah",
    word = "word"
}
export enum QuizType {
    wordGuess = "wordGuess",
    multipleChoice = "multipleChoice"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addAyahToLesson(lessonId: string, text: string, translation: string | null, reference: string | null): Promise<void>;
    addLessonWithWordsAndAyahs(request: AddLessonWithWordsRequest): Promise<AddLessonWithWordsResponse>;
    addWordToLesson(arabic: string, albanianMeanings: Array<string>, forms: Array<string>, formMeanings: Array<string>, lessonId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkWordInLessons(word: string): Promise<boolean>;
    createLesson(title: string, content: string, visibleToStudents: boolean): Promise<string>;
    createNote(content: string, associatedId: string, noteType: NoteType): Promise<string>;
    createQuiz(quizType: QuizType, title: string): Promise<string>;
    deleteLesson(lessonId: string): Promise<void>;
    deleteNote(noteId: string): Promise<void>;
    deleteQuiz(quizId: string): Promise<void>;
    deleteWordFromLesson(word: string, lessonId: string): Promise<void>;
    getActiveLessonWithWords(): Promise<LessonWithWords | null>;
    getActiveLessonWithWordsAndAyahs(): Promise<{
        ayahs: Array<Ayah>;
        lesson: Lesson;
        words: Array<Word>;
    } | null>;
    getAllActiveLessons(): Promise<Array<Lesson>>;
    getAllLessons(): Promise<Array<Lesson>>;
    getAllLessonsWithWordsAndAyahs(): Promise<Array<{
        ayahs: Array<Ayah>;
        lesson: Lesson;
        words: Array<Word>;
    }>>;
    getAllUserProfiles(): Promise<Array<StableUserProfile>>;
    getAllVocabulary(): Promise<Array<Word>>;
    getCallerUserProfile(): Promise<StableUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLessonAyahs(lessonId: string): Promise<Array<Ayah>>;
    getLessonById(lessonId: string): Promise<{
        ayahs: Array<Ayah>;
        lesson: Lesson;
        words: Array<Word>;
    } | null>;
    getLessonWords(): Promise<Array<[string, Array<string>]>>;
    getLessonsByAuthor(author: Principal): Promise<Array<Lesson>>;
    getNotesByAssociatedId(user: Principal, associatedId: string): Promise<Array<Note>>;
    getNotesByUser(user: Principal): Promise<Array<Note>>;
    getQuiz(quizId: string): Promise<Quiz | null>;
    getQuizzes(): Promise<Array<Quiz>>;
    getRandomWords(): Promise<Array<Word>>;
    getUserProfile(user: Principal): Promise<StableUserProfile | null>;
    getVisibleLessons(): Promise<Array<Lesson>>;
    getWordsByLesson(lessonId: string): Promise<Array<Word>>;
    initializeAccessControl(): Promise<void>;
    isAdmin(user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    promoteToTeacher(user: Principal): Promise<void>;
    registerProfile(name: string): Promise<void>;
    resetAppData(): Promise<void>;
    setLessonActive(lessonId: string, isActive: boolean): Promise<void>;
    setLessonVisibility(lessonId: string, visibleToStudents: boolean): Promise<void>;
    updateLesson(lessonId: string, title: string, content: string, visibleToStudents: boolean): Promise<void>;
    updateLessonAyah(lessonId: string, ayahIndex: bigint, newText: string, newTranslation: string | null, newReference: string | null): Promise<void>;
    updateNote(noteId: string, content: string): Promise<void>;
    updateProfile(name: string, avatar: ExternalBlob | null): Promise<void>;
    updateQuiz(quizId: string, title: string, quizType: QuizType): Promise<void>;
    updateWord(arabic: string, albanianMeanings: Array<string>, forms: Array<string>, formMeanings: Array<string>, lessonId: string): Promise<void>;
    uploadLessonMaterial(file: ExternalBlob): Promise<ExternalBlob>;
}
import type { AddLessonWithWordsRequest as _AddLessonWithWordsRequest, Ayah as _Ayah, ExternalBlob as _ExternalBlob, Lesson as _Lesson, LessonWithWords as _LessonWithWords, Note as _Note, NoteType as _NoteType, Quiz as _Quiz, QuizType as _QuizType, StableUserProfile as _StableUserProfile, Time as _Time, UserRole as _UserRole, Word as _Word, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAyahToLesson(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAyahToLesson(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAyahToLesson(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addLessonWithWordsAndAyahs(arg0: AddLessonWithWordsRequest): Promise<AddLessonWithWordsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addLessonWithWordsAndAyahs(to_candid_AddLessonWithWordsRequest_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLessonWithWordsAndAyahs(to_candid_AddLessonWithWordsRequest_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWordToLesson(arg0: string, arg1: Array<string>, arg2: Array<string>, arg3: Array<string>, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWordToLesson(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWordToLesson(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkWordInLessons(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkWordInLessons(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkWordInLessons(arg0);
            return result;
        }
    }
    async createLesson(arg0: string, arg1: string, arg2: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(arg0, arg1, arg2);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string, arg2: NoteType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, to_candid_NoteType_n16(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, to_candid_NoteType_n16(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createQuiz(arg0: QuizType, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(to_candid_QuizType_n18(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(to_candid_QuizType_n18(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async deleteLesson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteQuiz(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return result;
        }
    }
    async deleteWordFromLesson(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWordFromLesson(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWordFromLesson(arg0, arg1);
            return result;
        }
    }
    async getActiveLessonWithWords(): Promise<LessonWithWords | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveLessonWithWords();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveLessonWithWords();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveLessonWithWordsAndAyahs(): Promise<{
        ayahs: Array<Ayah>;
        lesson: Lesson;
        words: Array<Word>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveLessonWithWordsAndAyahs();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveLessonWithWordsAndAyahs();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveLessons();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveLessons();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLessons();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLessons();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLessonsWithWordsAndAyahs(): Promise<Array<{
        ayahs: Array<Ayah>;
        lesson: Lesson;
        words: Array<Word>;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLessonsWithWordsAndAyahs();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLessonsWithWordsAndAyahs();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<StableUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVocabulary(): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVocabulary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVocabulary();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<StableUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonAyahs(arg0: string): Promise<Array<Ayah>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonAyahs(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonAyahs(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonById(arg0: string): Promise<{
        ayahs: Array<Ayah>;
        lesson: Lesson;
        words: Array<Word>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonById(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonById(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonWords(): Promise<Array<[string, Array<string>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonWords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonWords();
            return result;
        }
    }
    async getLessonsByAuthor(arg0: Principal): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsByAuthor(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsByAuthor(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByAssociatedId(arg0: Principal, arg1: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByAssociatedId(arg0, arg1);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByAssociatedId(arg0, arg1);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByUser(arg0: Principal): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByUser(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByUser(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuiz(arg0: string): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizzes(): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzes();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzes();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomWords(): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomWords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomWords();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<StableUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisibleLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisibleLessons();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisibleLessons();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWordsByLesson(arg0: string): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWordsByLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWordsByLesson(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async promoteToTeacher(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToTeacher(arg0);
            return result;
        }
    }
    async registerProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0);
            return result;
        }
    }
    async resetAppData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAppData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAppData();
            return result;
        }
    }
    async setLessonActive(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLessonActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLessonActive(arg0, arg1);
            return result;
        }
    }
    async setLessonVisibility(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLessonVisibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLessonVisibility(arg0, arg1);
            return result;
        }
    }
    async updateLesson(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateLessonAyah(arg0: string, arg1: bigint, arg2: string, arg3: string | null, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLessonAyah(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLessonAyah(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateNote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, await to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, await to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateQuiz(arg0: string, arg1: string, arg2: QuizType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuiz(arg0, arg1, to_candid_QuizType_n18(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuiz(arg0, arg1, to_candid_QuizType_n18(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateWord(arg0: string, arg1: Array<string>, arg2: Array<string>, arg3: Array<string>, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWord(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWord(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async uploadLessonMaterial(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadLessonMaterial(await to_candid_ExternalBlob_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadLessonMaterial(await to_candid_ExternalBlob_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Ayah_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ayah): Ayah {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LessonWithWords_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonWithWords): LessonWithWords {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_NoteType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteType): NoteType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_QuizType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizType): QuizType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Quiz_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quiz): Quiz {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_StableUserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StableUserProfile): Promise<StableUserProfile> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LessonWithWords]): LessonWithWords | null {
    return value.length === 0 ? null : from_candid_LessonWithWords_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        ayahs: Array<_Ayah>;
        lesson: _Lesson;
        words: Array<_Word>;
    }]): {
    ayahs: Array<Ayah>;
    lesson: Lesson;
    words: Array<Word>;
} | null {
    return value.length === 0 ? null : from_candid_record_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StableUserProfile]): Promise<StableUserProfile | null> {
    return value.length === 0 ? null : await from_candid_StableUserProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : from_candid_Quiz_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lesson: _Lesson;
    words: Array<_Word>;
}): {
    lesson: Lesson;
    words: Array<Word>;
} {
    return {
        lesson: from_candid_Lesson_n23(_uploadFile, _downloadFile, value.lesson),
        words: value.words
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    createdAt: _Time;
    isActive: boolean;
    author: Principal;
    updatedAt: [] | [_Time];
    visibleToStudents: boolean;
}): {
    id: string;
    title: string;
    content: string;
    createdAt: Time;
    isActive: boolean;
    author: Principal;
    updatedAt?: Time;
    visibleToStudents: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        isActive: value.isActive,
        author: value.author,
        updatedAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.updatedAt)),
        visibleToStudents: value.visibleToStudents
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ayahs: Array<_Ayah>;
    lesson: _Lesson;
    words: Array<_Word>;
}): {
    ayahs: Array<Ayah>;
    lesson: Lesson;
    words: Array<Word>;
} {
    return {
        ayahs: from_candid_vec_n28(_uploadFile, _downloadFile, value.ayahs),
        lesson: from_candid_Lesson_n23(_uploadFile, _downloadFile, value.lesson),
        words: value.words
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    reference: [] | [string];
    translation: [] | [string];
}): {
    text: string;
    reference?: string;
    translation?: string;
} {
    return {
        text: value.text,
        reference: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.reference)),
        translation: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.translation))
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    principalId: string;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    role: string;
    principalId: string;
    avatar?: ExternalBlob;
}> {
    return {
        name: value.name,
        role: value.role,
        principalId: value.principalId,
        avatar: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    createdAt: _Time;
    user: Principal;
    noteType: _NoteType;
    updatedAt: [] | [_Time];
    associatedId: string;
}): {
    id: string;
    content: string;
    createdAt: Time;
    user: Principal;
    noteType: NoteType;
    updatedAt?: Time;
    associatedId: string;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        user: value.user,
        noteType: from_candid_NoteType_n45(_uploadFile, _downloadFile, value.noteType),
        updatedAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.updatedAt)),
        associatedId: value.associatedId
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: _Time;
    author: Principal;
    updatedAt: [] | [_Time];
    quizType: _QuizType;
}): {
    id: string;
    title: string;
    createdAt: Time;
    author: Principal;
    updatedAt?: Time;
    quizType: QuizType;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        author: value.author,
        updatedAt: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.updatedAt)),
        quizType: from_candid_QuizType_n50(_uploadFile, _downloadFile, value.quizType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ayah: null;
} | {
    word: null;
}): NoteType {
    return "ayah" in value ? NoteType.ayah : "word" in value ? NoteType.word : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wordGuess: null;
} | {
    multipleChoice: null;
}): QuizType {
    return "wordGuess" in value ? QuizType.wordGuess : "multipleChoice" in value ? QuizType.multipleChoice : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ayah>): Array<Ayah> {
    return value.map((x)=>from_candid_Ayah_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    ayahs: Array<_Ayah>;
    lesson: _Lesson;
    words: Array<_Word>;
}>): Array<{
    ayahs: Array<Ayah>;
    lesson: Lesson;
    words: Array<Word>;
}> {
    return value.map((x)=>from_candid_record_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StableUserProfile>): Promise<Array<StableUserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StableUserProfile_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quiz>): Array<Quiz> {
    return value.map((x)=>from_candid_Quiz_n48(_uploadFile, _downloadFile, x));
}
function to_candid_AddLessonWithWordsRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddLessonWithWordsRequest): _AddLessonWithWordsRequest {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Ayah_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Ayah): _Ayah {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NoteType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteType): _NoteType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_QuizType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizType): _QuizType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n54(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    ayahs: Array<Ayah>;
    visibleToStudents: boolean;
    words: Array<Word>;
}): {
    title: string;
    content: string;
    ayahs: Array<_Ayah>;
    visibleToStudents: boolean;
    words: Array<_Word>;
} {
    return {
        title: value.title,
        content: value.content,
        ayahs: to_candid_vec_n11(_uploadFile, _downloadFile, value.ayahs),
        visibleToStudents: value.visibleToStudents,
        words: value.words
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    reference?: string;
    translation?: string;
}): {
    text: string;
    reference: [] | [string];
    translation: [] | [string];
} {
    return {
        text: value.text,
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        translation: value.translation ? candid_some(value.translation) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteType): {
    ayah: null;
} | {
    word: null;
} {
    return value == NoteType.ayah ? {
        ayah: null
    } : value == NoteType.word ? {
        word: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizType): {
    wordGuess: null;
} | {
    multipleChoice: null;
} {
    return value == QuizType.wordGuess ? {
        wordGuess: null
    } : value == QuizType.multipleChoice ? {
        multipleChoice: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Ayah>): Array<_Ayah> {
    return value.map((x)=>to_candid_Ayah_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
